global:
  sendAnonymousUsage: false
  checkNewVersion: false

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"
  
api:
  dashboard: true
  insecure: true
  debug: true

log:
  level: "INFO"
  format: "common"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedbydefault: false
