version: '3.8'
services:
  reverse-proxy:
    image: traefik:v2.2

    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /Users/franck/Git/traefik/traefik.yaml:/etc/traefik/traefik.yml

  whoami:
    image: containous/whoami
    labels:
      - "traefik.http.routers.whoami.rule=Host(`vault.fs0c3ty.ovh`)"





#Installation Id: 993c00da-a4a2-4f99-98cc-ac2700b65db1
#Installation Key: 9GklSlsPJRiETlurQC3B